### PR TITLE
Support for es6 imports + vanilla browser usage

### PR DESCRIPTION
**Pull request by mhamann**
- Convert build to webpack
- Use webpack-dev-server for development
- Replace karma with jest for tests
- Replace gulp with npm for scripts/builds

### CODE REVIEW

**Comment by mhamann** [comment]
@mohsen1 as promised, here's a re-do of the previous PR, which I believe should address all of your concerns.

Because I've removed bower from this build (and now always bundle `json-formatter-js`), I would recommend releasing this as `2.0.0` to avoid breaking any users. Even though there are not new features, the packaging changes could cause unintended side-effects for existing usage.

Let me know if you have any further comments or concerns.

Thanks!

**Comment by mhamann** [comment]
@mohsen1 any chance you can look at and merge this PR this week?

**Comment by mohsen1** [comment]
I'll take a look tonight. Sorry about the delay

**Comment by mhamann** [comment]
@mohsen1 just another gentle reminder ;-) (Life is crazy, I know!)

**Comment by mohsen1** [comment]
Thanks!

**Comment by mhamann** [comment]
Thank YOU!

**Pull request merged**
